package com.example.agenda.pojos;
// Generated 12-sep-2018 12:10:41 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorias generated by hbm2java
 */
@Entity
@Table(name = "categorias", catalog = "agenda")
public class Categorias implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer idcategorias;
	private String nombre;
	private String descripcion;
	private Empleados empleado;

	public Categorias() {
	}

	public Categorias(String nombre) {
		this.nombre = nombre;
	}

	public Categorias(String nombre, String descripcion, Empleados empleado) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.empleado = empleado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcategorias", unique = true, nullable = false)
	public Integer getIdcategorias() {
		return this.idcategorias;
	}

	public void setIdcategorias(Integer idcategorias) {
		this.idcategorias = idcategorias;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorias")
	public Empleados getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleados empleado) {
		this.empleado = empleado;
	}

}
